from enum import Enum

class CMD(Enum):
    PING = 0
    SEND_TWO_INTS = 1
    SEND_THREE_FLOATS = 2
    ECHO = 3
    DANCE = 4
    SET_VEL = 5
    GET_TIME_MILLIS = 6
    SEND_TIME_DATA = 7
    GET_TEMP_READINGS = 8
    DATA_RATE = 9
    GET_IMU_READINGS = 10
    START_RECORDING = 11
    STOP_RECORDING = 12
    GET_DIST_READINGS = 13
    GET_ALL_READINGS = 14
    SET_MOTOR_JOB = 15
    SET_MOTOR_SEQUENCE = 16
    SET_PID_VALUES = 17
    SET_SETPOINT = 18
    START_PID = 19
    STOP_PID = 20
    GET_DRIVE_DATA = 21
    DO_DRIFT = 22
    COLLECT_MAPPING_DATA = 23