; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:regular]
platform = https://github.com/nigelb/platform-apollo3blue.git
board = SparkFun_RedBoard_Artemis_Nano
framework = arduino
platform_packages = 
    framework-arduinoapollo3 @ https://github.com/sparkfun/Arduino_Apollo3.git
lib_deps = 
	sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@^1.3.2
	arduino-libraries/ArduinoBLE@^1.5.0
	sparkfun/SparkFun VL53L1X 4m Laser Distance Sensor@^1.2.12
monitor_speed = 115200


[env:debug]
platform = https://github.com/nigelb/platform-apollo3blue.git
board = SparkFun_RedBoard_Artemis_Nano
framework = arduino
platform_packages = 
    framework-arduinoapollo3 @ https://github.com/sparkfun/Arduino_Apollo3.git
lib_deps = 
	sparkfun/SparkFun 9DoF IMU Breakout - ICM 20948 - Arduino Library@^1.3.2
	arduino-libraries/ArduinoBLE@^1.5.0
	sparkfun/SparkFun VL53L1X 4m Laser Distance Sensor@^1.2.12
monitor_speed = 115200
build_flags = -DDEBUG_ENABLED